language: node_js
node_js:
  - "node"

sudo: required
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell

before_script:
  - sleep 15
  - cd wattmail
  - npm install 

after_script:
  - npm start
